### ISSUE TITLE
module 'torch' has no attribute 'device'

### ISSUE THREAD

**Issue by gitassia** [xhlulu/dl-translate#43]
Hello , @xhlulu 
Please find attached the part of the tutorial that I tried to execute and where I find the error.
NB : I used the guide of Pytorch to install torch according to the command appropriate to my system which is: pip3 install torch torchvision torchaudio .
The version of torch is 1.10.1 and  my python  version  is 3.8.5 .
![image](https://user-images.githubusercontent.com/57732105/148654214-8bcb45b9-d55b-4074-95a2-01122613f20a.png)

![image](https://user-images.githubusercontent.com/57732105/148654179-cb8a4237-fd8d-42ad-ab08-a9ba6821d4e1.png)

Thank you for your help.

**Comment by xhlulu** [comment]
make sure you are using `python3` if you use pip3, or `python` if you used pip. Sometimes both coexist but are not the same thing.

Also check inside your script if you can import torch and call torch device. If that doesn't work there's something wrong with the setup and you should try again installing torch.

Also recommend listing your os. If you are using windows, please use WSL 2.0 with Ubuntu 18 as I have not tried on windows PowerShell.

**Comment by xhlulu** [comment]
Also please post your complete code, as well as what commands you wrote from installation to when you execute it. That would be helpful

**Comment by gitassia** [comment]
I am using python 3, and pip3. I tried to import torch and no error appeared but when I tried to import torch.device that error appeared again. I have already install and reinstall torch and the problem still exist.
For the code I used exactly what was written in the tutorial and when I got this error, I uninstalled and reinstalled torch according to the pytorch guide thinking that it is a version change but apparently it is not the case. I also tried a solution on the web with torch.cuda but it didn't fix the problem and it also mentions torch has no attribute named cuda. @xhlulu

**Comment by xhlulu** [comment]
I think there's a problem with your torch installation. Unfortunately I'm no familiar with how torch works and can't point you to a different direction other than check torch.__version__

You might want to look through the issues on the torch repository.

**Comment by xhlulu** [comment]
Or try installing with python -m pip install torch

**Comment by xhlulu** [comment]
can you run the following code in python?

```
import torch

print(torch.__version__)
print(torch.device)
```

and let me know if that creates an error?

**Comment by gitassia** [comment]
yes of course here is the error, I think I will have to reinstall all the packages and try again maybe there is a confusion between the names so I can use this command:  pip uninstall dl-translate  @xhlulu 

![image](https://user-images.githubusercontent.com/57732105/148677669-7459370d-baf8-4538-93f9-9dd11fc60ccd.png)

**Comment by xhlulu** [comment]
Likely a confusion. Make sure there's no file named torch.py in the same directory as your code.

**Comment by xhlulu** [comment]
@gitassia Since this is an issue with `torch`, I recommend you to open an issue on https://github.com/pytorch/pytorch/issues and maybe link to this issue if relevant. I'll close this for now.
